### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Bacring** [Alkohole/machine-reading-text#2]
how call function to press button 'start play' with javascript
send me code to i can run it console f12
![c3bZrTansf](https://github.com/user-attachments/assets/a4053ba0-6550-42ac-9036-3ad503064b03)

**Comment by Bacring** [comment]
Also add voices:

marina
dasha
lera
masha
julia
alexander
anton
kirill
filipp
madirus

for ru_RU

**Comment by Alkohole** [comment]
I don't know, first of all this function should be defined in the glabal scope, only after that you can access it via console. (You can study [text.modern.min.js](https://github.com/Alkohole/machine-reading-text/blob/main/js/text.modern.min.js), if I'm not mistaken the button is accessed in the function on line 11567).

About the other voices, I would love to add them, but they are simply not supported or I have not found the right index of these models to address.

**Comment by Bacring** [comment]
Я через js с помощью getelementbyid получивпю кнопки имитирую елик и оно не срабатывает

**Comment by Bacring** [comment]
Можешь помочь чтоб можно вызывать клик на кнопку и чтоб озвучка началась

**Comment by Bacring** [comment]
Через джаваскрипт

**Comment by Bacring** [comment]
Можешь сделать чтоб при вызове ивента клика на кнопку выполнять та функция озвучки текста которая у тебя есть там

**Comment by Bacring** [comment]
капец ты безграмотный бездарь сделать не можешь

**Comment by Alkohole** [comment]
Извините конечно, но с какого перепугу вы вдруг решили, что я обязан бежать и спотыкаться исполняя ваши хотелки? Вы не можете решить свою хотелку, а бездарь в итоге я, гениально.

**Comment by Bacring** [comment]
Просто без данной функции я не могу реализовать свой код, можешь сделать пожалуйста чтоб вызов ивента клика на кнопку через консоль f12 запускал эту кнопку и воспроизводил или дать пример кода для вставки в консоль в f12, после которого озвучка запускается и читает то что в textarea, буду благодарен

**Comment by Bacring** [comment]
Такой ленивыи сын шмры, обиженыи жизнью, пишет код на гитхабе, не зная где запуститься и показать свои продукт, такой овощ
В жизни бы я тебя знал просто довел бы тебя до петли, потому что ты слабыи
